import openai
import json

# Replace 'your_api_key_here' with your actual OpenAI API key
openai.api_key = ''

def generate_access_control_json(user_request):
    # Refine the prompt to guide the model to produce the desired JSON structure
    prompt = f"""
    Generate an access control policy JSON based on the following requirements:
    - User Request: "{user_request}"
    - Action should be within a smart home environment.
    - Include fields for trigger, condition, decision, and actions.
    - Example structure for guidance:
    {{
      "name": "shadowConn",
      "trigger": {{
        "src": {{
          "user": "U1",
          "platform": ["Alexa", "Smartthings", "Google Home", "Apple HomeKit"],
          "device": ""
        }},
        "dst": {{
          "user": "U2",
          "platform": ["Alexa", "Smartthings", "Google Home", "Apple HomeKit"],
          "device": ""
        }}
      }},
      "condition": {{
        "location": ["living room", "bedroom", "kitchen", "garage"],
        "time": ""
      }},
      "decision": {{
        "requester": "U2",
        "approver": "U1",
        "outcome": ["accept", "reject"]
      }},
      "actions": [{{...}}]
    }}
    """

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=1500
    )

    # Extracting the text generated by the model
    generated_text = response["choices"][0]["message"]["content"].strip()

    try:
        # Convert the generated text into JSON to ensure it's correctly formatted
        parsed_json = json.loads(generated_text)
        print(json.dumps(parsed_json, indent=4))
        return parsed_json
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return None

# Example usage
user_request = "U2 wants to turn on a switch in the living room."
generate_access_control_json(user_request)
